typography_spectrum: 0.9299782202579081
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5862185715232044
  lightness: 0.11406286689452827
  saturation: 0.37176436302252114
  rhythmicContrast: 0.017328107496723533
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.390510173747316
analytics:
  google: null
  facebook: null
  twitter: null
name: Ancient Secrets
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: making new sites easier
description: this is a new site by Symbient
purpose: []
